Greeting.create(message: 'Hello Touha!')
Greeting.create(message: 'Hello Abel!')
Greeting.create(message: 'Hello Said!')
Greeting.create(message: 'Hello Ashour!')
Greeting.create(message: 'Hello Techie!')